guisheng:
    build: .
    container_name: guisheng
    net: "host"
    env_file:
        - guisheng.env
    command: gunicorn --name guisheng -b 0.0.0.0:8888 -w 2 wsgi:app
    ports:
        - "8888:8888"
    volumes:
        - .:/guisheng